// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.42000
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace SM64_ROM_Manager.Publics.My.Resources
{

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
    /// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    public class FileDialogFilters
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileDialogFilters() : base()
        {
        }

        /// <summary>
        /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SM64_ROM_Manager.Publics.FileDialogFilters", typeof(FileDialogFilters).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die All supported formats|*.emf;*.bmp;*.gif;*.icon;*.jpg;*.jpeg;*.png;*.tiff;*.wmf ähnelt.
        /// </summary>
        public static string FilterPictureFormats_All
        {
            get
            {
                return ResourceManager.GetString("FilterPictureFormats_All", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Portable Network Graphic (*.png)|*.png|Tagged Image File (*.tiff)|*.tiff|Windows Metafile (*.wmf)|*.wmf|Enhanced Windows Metafile (*.emf)|*.emf|Bitmap (*.bmp)|*.bmp|GIF (*.gif)|*.gif|Icon (*.ico)|*.icon|Joint Photographic Experts Group (*.jpg)|*.jpg ähnelt.
        /// </summary>
        public static string FilterPictureFormats_Single
        {
            get
            {
                return ResourceManager.GetString("FilterPictureFormats_Single", resourceCulture);
            }
        }
    }
}