//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM64_ROM_Manager.My.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BehaviorBankManagerLangRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BehaviorBankManagerLangRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SM64_ROM_Manager.RomManager.Language_Resources.Behavior_Bank_Manager.BehaviorBank" +
                            "ManagerLangRes", typeof(BehaviorBankManagerLangRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure to disable the global behavior bank?&lt;br/&gt;The pointers will be resetted to vanilla. After this step is done, you can&apos;t revert it.&lt;br/&gt;You can re-enable the global behavior bank every time, but then it will be created from the vanilla bank 0x13 again. ähnelt.
        /// </summary>
        internal static string Msg_DisableGlobalBehaviorBank {
            get {
                return ResourceManager.GetString("Msg_DisableGlobalBehaviorBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disable Global Behavior Bank ähnelt.
        /// </summary>
        internal static string Msg_DisableGlobalBehaviorBank_Titel {
            get {
                return ResourceManager.GetString("Msg_DisableGlobalBehaviorBank_Titel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error happend at compiling your behavior script. Ensure folling points:
        ///- Every byte has to be seperate: 01 0A C9 ...
        ///- Every command in your script must have the correct length
        ///- If you edit a vanilla behavior script, it can&apos;t be larger then the original. ähnelt.
        /// </summary>
        internal static string Msg_ErrorCompilingScript {
            get {
                return ResourceManager.GetString("Msg_ErrorCompilingScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error at compiling script ähnelt.
        /// </summary>
        internal static string Msg_ErrorCompilingScriptTitel {
            get {
                return ResourceManager.GetString("Msg_ErrorCompilingScriptTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sure that you want to remove this behavior? ähnelt.
        /// </summary>
        internal static string Msg_RemoveBehavior {
            get {
                return ResourceManager.GetString("Msg_RemoveBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove Behavior ähnelt.
        /// </summary>
        internal static string Msg_RemoveBehaviorTitel {
            get {
                return ResourceManager.GetString("Msg_RemoveBehaviorTitel", resourceCulture);
            }
        }
    }
}
