// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.42000
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace SM64_ROM_Manager.UserRequests.GUI.My.Resources
{

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
    /// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class UserRequestGuiLangRes
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserRequestGuiLangRes() : base()
        {
        }

        /// <summary>
        /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SM64_ROM_Manager.UserRequests.GUI.UserRequestGuiLangRes", typeof(UserRequestGuiLangRes).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die An error happend at sending your request. ähnelt.
        /// </summary>
        internal static string MsgBox_ErrorSendingRequest
        {
            get
            {
                return ResourceManager.GetString("MsgBox_ErrorSendingRequest", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Error sending request ähnelt.
        /// </summary>
        internal static string MsgBox_ErrorSendingRequest_Titel
        {
            get
            {
                return ResourceManager.GetString("MsgBox_ErrorSendingRequest_Titel", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die The maximum size of all attachments together is 250 MiB for security reasons. Please reduce it e.g. packing your files to an archive. ähnelt.
        /// </summary>
        internal static string MsgBox_IncludedBigFiles
        {
            get
            {
                return ResourceManager.GetString("MsgBox_IncludedBigFiles", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Files to big ähnelt.
        /// </summary>
        internal static string MsgBox_IncludedBigFiles_Titel
        {
            get
            {
                return ResourceManager.GetString("MsgBox_IncludedBigFiles_Titel", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die The request was send successfully! ähnelt.
        /// </summary>
        internal static string MsgBox_SendingRequestSuccess
        {
            get
            {
                return ResourceManager.GetString("MsgBox_SendingRequestSuccess", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Request sent successfull! ähnelt.
        /// </summary>
        internal static string MsgBox_SendingRequestSuccess_Titel
        {
            get
            {
                return ResourceManager.GetString("MsgBox_SendingRequestSuccess_Titel", resourceCulture);
            }
        }
    }
}