// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.42000
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;

namespace SM64_ROM_Manager.My.Resources
{

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
    /// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    public class MyIcons
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyIcons() : base()
        {
        }

        /// <summary>
        /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SM64_ROM_Manager.MyIcons", typeof(MyIcons).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_about_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_about_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_add_node_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_add_node_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_add_subnode_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_add_subnode_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_arrow_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_arrow_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_arrow_40px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_arrow_40px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_cancel_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_cancel_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_chevron_down_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_chevron_down_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_chevron_up_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_chevron_up_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_coins_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_coins_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_collapse_arrow_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_collapse_arrow_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_color_dropper_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_color_dropper_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_controller_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_controller_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_copy_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_copy_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_cut_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_cut_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_delete_2_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_delete_2_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_delete_node_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_delete_node_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_delete_sign_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_delete_sign_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_delete_sign_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_delete_sign_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_delete_subnode_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_delete_subnode_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_download_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_download_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_downloading_updates_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_downloading_updates_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_edit_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_edit_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_edit_node_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_edit_node_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_error_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_error_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_expand_arrow_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_expand_arrow_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_export_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_export_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_export_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_export_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_filled_star_location_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_filled_star_location_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_fit_to_width_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_fit_to_width_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_folder_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_folder_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_forward_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_forward_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_help_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_help_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_high_importance_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_high_importance_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_import_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_import_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_import_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_import_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_info_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_info_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_map_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_map_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_merge_horizontal_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_merge_horizontal_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_message_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_message_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_move_node_down_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_move_node_down_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_move_node_up_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_move_node_up_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_music_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_music_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_open_folder_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_open_folder_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_paper_plane_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_paper_plane_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_paste_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_paste_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_paste_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_paste_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_paste_special_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_paste_special_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_pills_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_pills_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_plugin_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_plugin_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_plus_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_plus_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_plus_math_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_plus_math_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_plus_math_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_plus_math_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_preview_pane_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_preview_pane_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_redo_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_redo_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_refresh_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_refresh_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_save_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_save_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_screenshot_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_screenshot_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_settings_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_settings_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_split_vertical_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_split_vertical_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_support_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_support_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_syringe_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_syringe_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_text_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_text_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_undo_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_undo_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_upload_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_upload_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static Bitmap icons8_variation_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_variation_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}