// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.42000
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Drawing;

namespace SM64_ROM_Manager.My.Resources
{

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
    /// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class MyOldIcons
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyOldIcons() : base()
        {
        }

        /// <summary>
        /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SM64_ROM_Manager.MyOldIcons", typeof(MyOldIcons).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Add_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("Add_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Edit_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("Edit_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap EditPicture_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("EditPicture_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Psychology_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("Psychology_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Psychology_34px
        {
            get
            {
                var obj = ResourceManager.GetObject("Psychology_34px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Refresh_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("Refresh_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Remove_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("Remove_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("Save_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save_18px
        {
            get
            {
                var obj = ResourceManager.GetObject("Save_18px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save_19px
        {
            get
            {
                var obj = ResourceManager.GetObject("Save_19px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Save_20px
        {
            get
            {
                var obj = ResourceManager.GetObject("Save_20px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SaveAll_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("SaveAll_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SaveAll_16px1
        {
            get
            {
                var obj = ResourceManager.GetObject("SaveAll_16px1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Shrink_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("Shrink_16px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Shrink_16px1
        {
            get
            {
                var obj = ResourceManager.GetObject("Shrink_16px1", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Shrink_32px
        {
            get
            {
                var obj = ResourceManager.GetObject("Shrink_32px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap Shrink_34px
        {
            get
            {
                var obj = ResourceManager.GetObject("Shrink_34px", resourceCulture);
                return (Bitmap)obj;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static Bitmap SMS_34px
        {
            get
            {
                var obj = ResourceManager.GetObject("SMS_34px", resourceCulture);
                return (Bitmap)obj;
            }
        }
    }
}