//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM64_ROM_Manager.ModelConverterGUI.My.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainModelconverter_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainModelconverter_Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SM64_ROM_Manager.ModelConverterGUI.Language_Resources.MainModelconverter_Resource" +
                            "s", typeof(MainModelconverter_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatic ähnelt.
        /// </summary>
        public static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solid (no anti alias) ähnelt.
        /// </summary>
        public static string Layer0 {
            get {
                return ResourceManager.GetString("Layer0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solid ähnelt.
        /// </summary>
        public static string Layer1 {
            get {
                return ResourceManager.GetString("Layer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Solid Decal ähnelt.
        /// </summary>
        public static string Layer2 {
            get {
                return ResourceManager.GetString("Layer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translucent Decal ähnelt.
        /// </summary>
        public static string Layer3 {
            get {
                return ResourceManager.GetString("Layer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alpha ähnelt.
        /// </summary>
        public static string Layer4 {
            get {
                return ResourceManager.GetString("Layer4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translucent ähnelt.
        /// </summary>
        public static string Layer5 {
            get {
                return ResourceManager.GetString("Layer5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translucent Decal ähnelt.
        /// </summary>
        public static string Layer6 {
            get {
                return ResourceManager.GetString("Layer6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translucent Decal ähnelt.
        /// </summary>
        public static string Layer7 {
            get {
                return ResourceManager.GetString("Layer7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your collision map is not triangulated. ähnelt.
        /// </summary>
        public static string MsgBox_ColMapIsnotTriangled {
            get {
                return ResourceManager.GetString("MsgBox_ColMapIsnotTriangled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Collision Map ähnelt.
        /// </summary>
        public static string MsgBox_ColMapIsnotTriangled_Title {
            get {
                return ResourceManager.GetString("MsgBox_ColMapIsnotTriangled_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error at loading Materials:&lt;br/&gt;{0} ähnelt.
        /// </summary>
        public static string MsgBox_ErrorLoadingMaterial {
            get {
                return ResourceManager.GetString("MsgBox_ErrorLoadingMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Material Error ähnelt.
        /// </summary>
        public static string MsgBox_ErrorLoadingMaterial_Title {
            get {
                return ResourceManager.GetString("MsgBox_ErrorLoadingMaterial_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your {0} is too big or your scaling is too large. Your collision map probably will have some issues after importing. ähnelt.
        /// </summary>
        public static string MsgBox_ModelTooBig {
            get {
                return ResourceManager.GetString("MsgBox_ModelTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Out of bounds ähnelt.
        /// </summary>
        public static string MsgBox_ModelTooBig_Title {
            get {
                return ResourceManager.GetString("MsgBox_ModelTooBig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die To use Assimp loader module, you need &lt;b&gt;Microsoft Visual C++ Redistributable 2017&lt;/b&gt; installed on your PC.&lt;br/&gt;&lt;br/&gt;&lt;b&gt;Download links:&lt;/b&gt;&lt;br/&gt;&lt;a href=&quot;&quot;&gt;https://aka.ms/vs/15/release/vc_redist.x64.exe&quot;&quot;&gt;vc_redist.x64.exe&lt;/a&gt; (for &lt;b&gt;64-bit&lt;/b&gt; systems)&lt;br/&gt;&lt;a href=&quot;&quot;&gt;https://aka.ms/vs/15/release/vc_redist.x86.exe&quot;&quot;&gt;vc_redist.x32.exe&lt;/a&gt; (for &lt;b&gt;32-bit&lt;/b&gt; systems) ähnelt.
        /// </summary>
        public static string MsgBox_MVCppMissing {
            get {
                return ResourceManager.GetString("MsgBox_MVCppMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microsoft Visual C++ Redistributable 2017 is missing ähnelt.
        /// </summary>
        public static string MsgBox_MVCppMissing_Title {
            get {
                return ResourceManager.GetString("MsgBox_MVCppMissing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your visual map is not triangulated. ähnelt.
        /// </summary>
        public static string MsgBox_VMapIsnotTriangled {
            get {
                return ResourceManager.GetString("MsgBox_VMapIsnotTriangled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Visual Map ähnelt.
        /// </summary>
        public static string MsgBox_VMapIsnotTriangled_Title {
            get {
                return ResourceManager.GetString("MsgBox_VMapIsnotTriangled_Title", resourceCulture);
            }
        }
    }
}
