// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.42000
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace SM64_ROM_Manager.PatchScripts
{


    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
/// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
/// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class MyIcons
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyIcons() : base()
        {
        }

        /// <summary>
    /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
    /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SM64_ROM_Manager.PatchScripts.MyIcons", typeof(MyIcons).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
    /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
    /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
    /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_cancel_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_cancel_16px", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_checkmark_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_checkmark_16px", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_delete_sign_16px_1
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_delete_sign_16px_1", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_downloading_updates_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_downloading_updates_16px", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_edit_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_edit_16px", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_open_folder_16px_1
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_open_folder_16px_1", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_play_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_play_16px", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_plus_math_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_plus_math_16px", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_save_16px_1
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_save_16px_1", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_search_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_search_16px", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
    /// Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
    /// </summary>
        internal static System.Drawing.Bitmap icons8_triggering_16px
        {
            get
            {
                var obj = ResourceManager.GetObject("icons8_triggering_16px", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }
    }
}