// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.42000
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace SM64_ROM_Manager.Updating.Administration.GUI.My.Resources
{

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
    /// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class UpdatingAdministrationLangRes
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdatingAdministrationLangRes() : base()
        {
        }

        /// <summary>
        /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SM64_ROM_Manager.Updating.Administration.GUI.UpdatingAdministrationLangRes", typeof(UpdatingAdministrationLangRes).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Alpha ähnelt.
        /// </summary>
        internal static string Channel_Alpha
        {
            get
            {
                return ResourceManager.GetString("Channel_Alpha", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Beta ähnelt.
        /// </summary>
        internal static string Channel_Beta
        {
            get
            {
                return ResourceManager.GetString("Channel_Beta", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Vorabverion ähnelt.
        /// </summary>
        internal static string Channel_PreRelease
        {
            get
            {
                return ResourceManager.GetString("Channel_PreRelease", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Stabil ähnelt.
        /// </summary>
        internal static string Channel_Stable
        {
            get
            {
                return ResourceManager.GetString("Channel_Stable", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string MsgBox_Error_Titel
        {
            get
            {
                return ResourceManager.GetString("MsgBox_Error_Titel", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Fehler beim hinzufügen des AddOns. ähnelt.
        /// </summary>
        internal static string MsgBox_ErrorAddingInstallerAddOn
        {
            get
            {
                return ResourceManager.GetString("MsgBox_ErrorAddingInstallerAddOn", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Paket wurde erfolgreich exportiert! ähnelt.
        /// </summary>
        internal static string MsgBox_PkgExportSuccess
        {
            get
            {
                return ResourceManager.GetString("MsgBox_PkgExportSuccess", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Paket exportiert ähnelt.
        /// </summary>
        internal static string MsgBox_PkgExportSuccess_Titel
        {
            get
            {
                return ResourceManager.GetString("MsgBox_PkgExportSuccess_Titel", resourceCulture);
            }
        }
    }
}