//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM64_ROM_Manager.My.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorDialogLangRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorDialogLangRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SM64_ROM_Manager.Rom_Manager.Language_Resources.Error_Dialog.ErrorDialogLangRes", typeof(ErrorDialogLangRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;u&gt;Feature description:&lt;/u&gt;&lt;br/&gt;{0} ähnelt.
        /// </summary>
        public static string FeatureDescription_BaseText {
            get {
                return ResourceManager.GetString("FeatureDescription_BaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exits the program and discards all unsaved changes. &lt;b&gt;This option is highly RECOMMENDED!&lt;/b&gt; ähnelt.
        /// </summary>
        public static string FeatureDescription_CloseProgram {
            get {
                return ResourceManager.GetString("FeatureDescription_CloseProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves some useful diagnostic data as a file in a location of your choosing. Please send this diagnostic file to the developer to help fix this error and, if necessary, to get help yourself. If you have activated the recording of extended diagnostic data, these will be included. ähnelt.
        /// </summary>
        public static string FeatureDescription_ExportErrorDiagnostic {
            get {
                return ResourceManager.GetString("FeatureDescription_ExportErrorDiagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore this error message (if the main program has&apos;t already been terminated by the error) and continues execution. &lt;b&gt;This option is expressly NOT recommended and should only be used if you know what you are doing!&lt;/b&gt; Possible consequences would be subsequent errors that lead to &lt;b&gt;new error messages&lt;/b&gt; or even &lt;b&gt;large data loss (e.g. in the ROM)&lt;/b&gt;. ähnelt.
        /// </summary>
        public static string FeatureDescription_IgnoreErrorMessage {
            get {
                return ResourceManager.GetString("FeatureDescription_IgnoreErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No description available. ähnelt.
        /// </summary>
        public static string FeatureDescription_NoDescription {
            get {
                return ResourceManager.GetString("FeatureDescription_NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saves some useful diagnostic data as a file and attaches the file to a new user request. You can fill some other informations and send the request directly to the developer. If you have activated the recording of extended diagnostic data, these will be included. ähnelt.
        /// </summary>
        public static string FeatureDescription_UploadErrorDiagnostic {
            get {
                return ResourceManager.GetString("FeatureDescription_UploadErrorDiagnostic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;u&gt;Are you sure&lt;/u&gt; to ignore this error message?&lt;br/&gt;This continues the execution of the main application. &lt;b&gt;This option is expressly NOT recommended and should only be used if you know what you are doing!&lt;/b&gt; Possible consequences would be subsequent errors that lead to &lt;b&gt;new error messages&lt;/b&gt; or even &lt;b&gt;large data loss in the project&lt;/b&gt;. ähnelt.
        /// </summary>
        public static string MsgBox_SureToIgnore {
            get {
                return ResourceManager.GetString("MsgBox_SureToIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore error message ähnelt.
        /// </summary>
        public static string MsgBox_SureToIgnore_Title {
            get {
                return ResourceManager.GetString("MsgBox_SureToIgnore_Title", resourceCulture);
            }
        }
    }
}
