//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SM64_ROM_Manager.My.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HUDOptionsLangRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HUDOptionsLangRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SM64_ROM_Manager.RomManager.GUI.Tools.HUDOptions.HUDOptionsLangRes", typeof(HUDOptionsLangRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Coins ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_CoinCounter {
            get {
                return ResourceManager.GetString("HUDPos_Counters_CoinCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counter ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_CoinCounter_Counter {
            get {
                return ResourceManager.GetString("HUDPos_Counters_CoinCounter_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_CoinCounter_Icon {
            get {
                return ResourceManager.GetString("HUDPos_Counters_CoinCounter_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_CoinCounter_X {
            get {
                return ResourceManager.GetString("HUDPos_Counters_CoinCounter_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lives ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_LiveCounter {
            get {
                return ResourceManager.GetString("HUDPos_Counters_LiveCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counter ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_LiveCounter_Counter {
            get {
                return ResourceManager.GetString("HUDPos_Counters_LiveCounter_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_LiveCounter_Icon {
            get {
                return ResourceManager.GetString("HUDPos_Counters_LiveCounter_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_LiveCounter_X {
            get {
                return ResourceManager.GetString("HUDPos_Counters_LiveCounter_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stars ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_StarCounter {
            get {
                return ResourceManager.GetString("HUDPos_Counters_StarCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counter ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_StarCounter_Counter {
            get {
                return ResourceManager.GetString("HUDPos_Counters_StarCounter_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_StarCounter_Icon {
            get {
                return ResourceManager.GetString("HUDPos_Counters_StarCounter_Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die X ähnelt.
        /// </summary>
        internal static string HUDPos_Counters_StarCounter_X {
            get {
                return ResourceManager.GetString("HUDPos_Counters_StarCounter_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Positions ähnelt.
        /// </summary>
        internal static string HUDPos_FirstContainer {
            get {
                return ResourceManager.GetString("HUDPos_FirstContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Main ähnelt.
        /// </summary>
        internal static string HUDPos_Main {
            get {
                return ResourceManager.GetString("HUDPos_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counters ähnelt.
        /// </summary>
        internal static string HUDPos_Main_Counters {
            get {
                return ResourceManager.GetString("HUDPos_Main_Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Timer ähnelt.
        /// </summary>
        internal static string HUDPos_Main_Timer {
            get {
                return ResourceManager.GetString("HUDPos_Main_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Counter ähnelt.
        /// </summary>
        internal static string HUDPos_Timer_Counter {
            get {
                return ResourceManager.GetString("HUDPos_Timer_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string HUDPos_Timer_Time {
            get {
                return ResourceManager.GetString("HUDPos_Timer_Time", resourceCulture);
            }
        }
    }
}
