// ------------------------------------------------------------------------------
// <auto-generated>
// Dieser Code wurde von einem Tool generiert.
// Laufzeitversion:4.0.30319.42000
// 
// Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
// der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace SM64_ROM_Manager.Updating.UpdateInstaller.My.Resources
{

    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    /// <summary>
    /// Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class UpdateInstallerGuiLangRes
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateInstallerGuiLangRes() : base()
        {
        }

        /// <summary>
        /// Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("SM64_ROM_Manager.Updating.UpdateInstaller.UpdateInstallerGuiLangRes", typeof(UpdateInstallerGuiLangRes).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        /// Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Copying new files ... ähnelt.
        /// </summary>
        internal static string Status_CopyingFiles
        {
            get
            {
                return ResourceManager.GetString("Status_CopyingFiles", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Finished! ähnelt.
        /// </summary>
        internal static string Status_Done
        {
            get
            {
                return ResourceManager.GetString("Status_Done", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Extracting update package ... ähnelt.
        /// </summary>
        internal static string Status_Extracting
        {
            get
            {
                return ResourceManager.GetString("Status_Extracting", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Removing files ... ähnelt.
        /// </summary>
        internal static string Status_RemovingFiles
        {
            get
            {
                return ResourceManager.GetString("Status_RemovingFiles", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Executing AddOn&apos;s ... ähnelt.
        /// </summary>
        internal static string Status_RunningAddOns
        {
            get
            {
                return ResourceManager.GetString("Status_RunningAddOns", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Waiting ... ähnelt.
        /// </summary>
        internal static string Status_Waiting
        {
            get
            {
                return ResourceManager.GetString("Status_Waiting", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Installing Updates ähnelt.
        /// </summary>
        internal static string String_UpdateIsRunning
        {
            get
            {
                return ResourceManager.GetString("String_UpdateIsRunning", resourceCulture);
            }
        }

        /// <summary>
        /// Sucht eine lokalisierte Zeichenfolge, die Installing Updates for {0} ... ähnelt.
        /// </summary>
        internal static string String_UpdatingApplicationX
        {
            get
            {
                return ResourceManager.GetString("String_UpdatingApplicationX", resourceCulture);
            }
        }
    }
}